// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_uat.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Q2Ee9iXyOAGCsBVtUdDgb5fVXdo6xwg',
    appId: '1:118836796888:web:2f906e07e7dc24674ee6ad',
    messagingSenderId: '118836796888',
    projectId: 'athena-uat-7e581',
    authDomain: 'athena-uat-7e581.firebaseapp.com',
    databaseURL: 'https://athena-uat-7e581-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'athena-uat-7e581.firebasestorage.app',
    measurementId: 'G-5HV4K73VC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq1YbblO3JSutU2y_56Fpg6gALxwSMcak',
    appId: '1:118836796888:android:0c346c33116d55eb4ee6ad',
    messagingSenderId: '118836796888',
    projectId: 'athena-uat-7e581',
    databaseURL: 'https://athena-uat-7e581-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'athena-uat-7e581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPsKgT4UulDKye7nHQqyS3nfXz2hD68V8',
    appId: '1:118836796888:ios:a305b33e7272ca6e4ee6ad',
    messagingSenderId: '118836796888',
    projectId: 'athena-uat-7e581',
    databaseURL: 'https://athena-uat-7e581-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'athena-uat-7e581.firebasestorage.app',
    iosBundleId: 'com.a4b.athenahuntdev',
  );
}
