// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGnQbsKpoI7yurfiCNAsyHIWFFTbycNJQ',
    appId: '1:71562081737:web:658491d4ef06967122a418',
    messagingSenderId: '71562081737',
    projectId: 'athena-owl-prod',
    authDomain: 'athena-owl-prod.firebaseapp.com',
    storageBucket: 'athena-owl-prod.firebasestorage.app',
    measurementId: 'G-E6RBKE2P8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxk9oMRNXCE2Z7O3ddgSype5NDps5s8xU',
    appId: '1:71562081737:android:0c8e5324e6391c4822a418',
    messagingSenderId: '71562081737',
    projectId: 'athena-owl-prod',
    storageBucket: 'athena-owl-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACYdUZEXRRzbkAlYqC3fm_ktir1cS25rk',
    appId: '1:71562081737:ios:c5127efe7ee8315322a418',
    messagingSenderId: '71562081737',
    projectId: 'athena-owl-prod',
    storageBucket: 'athena-owl-prod.firebasestorage.app',
    iosBundleId: 'com.a4b.athenahuntdev',
  );
}
